### PR TITLE
Implementing Layout Builder in profile

### PR DESCRIPTION
**Pull request by piggito**
Copy from #251 :

- Removed field_layout from modules and configs
- Created 2 new block type to be used in Layout Builder "content" mode instead of paragraph
- Added layout_builder_modal for better UX
- Added layout_builder_restrictions for better UX
- Added layout_library for ability to select layout when publishing a node
- Recreated layout for basic_page CT and paragraphs using LB
- Configured layout_builder_restrictions on basic_page CT 
- Find patches for issues in watchdog logs
- Checked D9 compatibility of modules added

### CODE REVIEW

**Comment by piggito** [comment]
> Check D9 compatibility of modules added
Fixed

**Comment by piggito** [comment]
> Find patches for issues in logs

Fixed with patches at https://www.drupal.org/project/lb_ux/issues/3106939#comment-13631471 and https://www.drupal.org/project/lb_ux/issues/3116402#comment-13631976

**Comment by davidferlay** [comment]
> > Find patches for issues in logs
> 
> Fixed with patches at https://www.drupal.org/project/lb_ux/issues/3106939#comment-13631471 and https://www.drupal.org/project/lb_ux/issues/3116402#comment-13631976

Found some more issues in dblog after creating such a node (using basic_page and content layout override) : image

1 - 
```
Location | http://172.19.0.4/layout_builder/move/block/overrides/node.2/1/1/third/6c60e92d-e617-4b00-be92-20d06ceeb4af/ae8db814-dfdc-421e-9bcd-376b892bb223?_wrapper_format=drupal_ajax
-- | --
http://172.19.0.4/node/2/layout
InvalidArgumentException: Invalid UUID "third" in Drupal\layout_builder\Section->getComponent() (line 177 of /var/www/html/web/core/modules/layout_builder/src/Section.php).
Error
```
2 - 
```
Location | http://172.19.0.4/layout_builder/add/block/overrides/node.2/1/third/inline_block%3Amedia?_wrapper_format=drupal_ajax&_wrapper_format=drupal_dialog&ajax_form=1
-- | --
http://172.19.0.4/node/2/layout
Warning: array_map(): Expected parameter 2 to be an array, bool given in Drupal\media_library\Plugin\Field\FieldWidget\MediaLibraryWidget::validateItems() (line 811 of /var/www/html/web/core/modules/media_library/src/Plugin/Field/FieldWidget/MediaLibraryWidget.php)#0 /var/www/html/web/core/includes/bootstrap.inc(600): _drupal_error_handler_real(2, 'array_map(): Ex...', '/var/www/html/w...', 811, Array) #1 [internal function]: _drupal_error_handler(2, 'array_map(): Ex...', '/var/www/html/w...', 811, Array) #2 /var/www/html/web/core/modules/media_library/src/Plugin/Field/FieldWidget/MediaLibraryWidget.php(811): array_map(Object(Closure), false) #3 [internal function]: Drupal\media_library\Plugin\Field\FieldWidget\MediaLibraryWidget::validateItems(Array, Object(Drupal\Core\Form\FormState)) #4 /var/www/html/web/core/lib/Drupal/Core/Form/FormValidator.php(82): call_user_func_array(Array, Array) #5 /var/www/html/web/core/lib/Drupal/Core/Form/FormValidator.php(275): Drupal\Core\Form\FormValidator->executeValidateHandlers(Array, Object(Drupal\Core\Form\FormState)) #6 /var/www/html/web/core/lib/Drupal/Core/Form/FormValidator.php(118): Drupal\Core\Form\FormValidator->doValidateForm(Array, Object(Drupal\Core\Form\FormState), 'layout_builder_...') #7 /var/www/html/web/core/lib/Drupal/Core/Form/FormBuilder.php(577): Drupal\Core\Form\FormValidator->validateForm('layout_builder_...', Array, Object(Drupal\Core\Form\FormState)) #8 /var/www/html/web/core/lib/Drupal/Core/Form/FormBuilder.php(320): Drupal\Core\Form\FormBuilder->processForm('layout_builder_...', Array, Object(Drupal\Core\Form\FormState)) #9 /var/www/html/web/core/lib/Drupal/Core/Controller/FormController.php(91): Drupal\Core\Form\FormBuilder->buildForm(Object(Drupal\layout_builder\Form\AddBlockForm), Object(Drupal\Core\Form\FormState)) #10 [internal function]: Drupal\Core\Controller\FormController->getContentResult(Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\Core\Routing\RouteMatch)) #11 /var/www/html/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array) #12 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(573): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #13 /var/www/html/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure)) #14 /var/www/html/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) #15 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(151): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #16 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #17 /var/www/html/web/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #18 /var/www/html/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #19 /var/www/html/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #20 /var/www/html/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true) #21 /var/www/html/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #22 /var/www/html/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #23 /var/www/html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #24 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(708): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #25 /var/www/html/web/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #26 {main}.
Warning


```

**Comment by davidferlay** [comment]
Found and added patch for remaining error in dblog

**Pull request merged**
