### PR TITLE
Replace MailHog with MailPit #449

### PR DESCRIPTION
**Pull request by Sergey-Orlov**
Used mailpit https://mailpit.axllent.org/ instead on Mailhog

Also updated **settings.local.php** to have proper symfony_mailer configuration for sendmail

### CODE REVIEW

**Comment by andypost** [comment]
Thank you, looks we can keep container name (port is the same) to prevent more renames on existing products

OTOH it could be easier to distinguish changes

**Comment by Sergey-Orlov** [comment]
> Thank you, looks we can keep container name (port is the same) to prevent more renames on existing products
> 
> OTOH it could be easier to distinguish changes

you mean that we only need to update image name in _docker/docker-compose.override.yml.default_ ?

**Comment by andypost** [comment]
Yes, changing image is a minimal required change

Just need to make sure the image size is not big, otherwise we'll need own image

**Comment by Sergey-Orlov** [comment]
Updated commit to have only image name changed.

Image size:
изображение

**Comment by andypost** [comment]
Looks like great replacement and easily propagatable
`skilldlabs/mailhog                latest              96940f3f1659   2 years ago     29.5MB`

**Pull request merged**
